version: 0.2

phases:
  preb_build:
    commands:
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 209479292855.dkr.ecr.eu-north-1.amazonaws.com
  build:
    commands:
      - docker build -t podcast .
      - docker tag podcast:latest 209479292855.dkr.ecr.eu-north-1.amazonaws.com/podcast:latest
  post_build:
    commands:
      - docker push 209479292855.dkr.ecr.eu-north-1.amazonaws.com/podcast:latest
