apiVersion: apps/v1
kind: Deployment
metadata:
  name: podcastback
  namespace: fari
  labels:
    app: podcastback
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podcastback
  template:
    metadata:
      labels:
        app: podcastback
    spec:
      containers:
        - name: podcastback
          image: 209479292855.dkr.ecr.eu-north-1.amazonaws.com/podcast:latest
          ports:
            - containerPort: 2000
       

---
apiVersion: v1
kind: Service
metadata:
  name: podcastback
  namespace: fari
spec:
  type: LoadBalancer
  selector:
    app: podcastback
  ports:
    - protocol: TCP
      port: 1000
      targetPort: 2000
