apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: fari
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        args:
           - server
           - /minio/data
           - --console-address
           - ":9001"
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: minio-storage
          mountPath: /minio/data
        envFrom:
        - secretRef:
            name: minio-secrets

      volumes:
      - name: minio-storage
        persistentVolumeClaim:
          claimName: minio-volume-claim

---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: fari
spec:
  type: NodePort
  selector:
    app: minio
  ports:
  - protocol: TCP
    port: 1100
    targetPort: 9000
    nodePort: 32200

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-volume
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db_psql_0001"


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-volume-claim
  namespace: fari
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
